### PR TITLE
Create thai food's menu

### PR DESCRIPTION
**Pull request by Nanokwok**
## Change in README.md

- Added link to Thai Food and name of contributor

## Change in menu.md

- Create Thai food's menu

### CODE REVIEW

**Comment by KikyoBRV** [comment]
You should add image as path of image not the link to image.

**Comment by Nanokwok** [comment]
Already fixed.

**Review by colarrbear — APPROVED** [review]
good.

**Review by KikyoBRV — APPROVED** [review]
Nice work!

**Review by JaofourthsOhappy — APPROVED** [review]
Look good to me!!

**Pull request merged**
